# Usa la imagen oficial de Nginx como base
FROM nginx:latest

# Copia el archivo HTML a la ubicación predeterminada de Nginx
COPY ./index.html /var/www/html/index.html

# Exponer el puerto 8082 del contenedor
EXPOSE 8082

# Cambia el puerto predeterminado de Nginx de 80 a 8082
RUN sed -i 's/listen 80;/listen 8082;/' /etc/nginx/conf.d/default.conf

# Ejecuta Nginx en modo foreground
CMD ["nginx", "-g", "daemon off;"]
