# Usa la imagen base de Nginx
FROM nginx:alpine

# Copia el archivo HTML al directorio por defecto de Nginx
COPY index.html /usr/share/nginx/html/

# Expone el puerto 8082
EXPOSE 8082

# Inicia el servidor Nginx
CMD ["nginx", "-g", "daemon off;"]
